---
title: "Ćwiczenie 6 (tidymodels)"
author: "Jakub Anczyk"
editor: visual
editor_options: 
  chunk_output_type: console
format: 
  html:
    toc: true
    toc-depth: 3
    toc-location: right
    toc-title: Spis Treści
    number-sections: true
    number-depth: 3
    embed-resources: true
    html-math-method: katex
    code-tools: true
    code-block-bg: true
    code-fold: show
    code-summary: "Show and hide code"
    link-external-icon: true
    link-external-newwindow: true
    smooth-scroll: true
    self-contained: true
    citation: true
    theme: 
        dark: solar
        light: flatly
    fontsize: 1.0em
    linestretch: 1.3
    fig-align: center
execute: 
  echo: true
  error: false
  warning: false
  output: true
---

## Załadowanie i wstępna transformacja danych

```{r}
#| eval: true
#| echo: false
#| output: false
#| warning: false
#| error: false
#| include: false

PackageNames <- c("dplyr", "tidymodels", "parsnip", "readr", "broom.mixed", "dotwhisker", "rstanarm", "GGally", "openair", "skimr", "nycflights13", "ggpubr", "leaps", "MASS", "caret", "forcats", "ranger", "modeldata", "tidymodels", "rpart.plot", "glmnet", "ranger", "readr","vip", "ggthemes")

PackageNames |> 
  purrr::map(.f = ~ require(.x, character.only = T))  

tidymodels_prefer()
Sys.setenv(LANG = "en")
```

### Załadowanie danych

```{r}
hotele <- 
  read_csv(file = "https://tidymodels.org/start/case-study/hotels.csv") |>  
  mutate_if(is.character, as.factor)  

hotele |> dim()
```

```{r}
hotele |> glimpse()
```


```{r}
hotele |>    
  count(children) |>    
  mutate(prop = n/sum(n)) |>    
  gt::gt() |>    
  gt::tab_header(title = "Zmienna objaśniana")
```


```{r}
set.seed(123)

splits <-
  initial_split(data = hotele,
                prop = 3 / 4,
                strata = "children")

hotel_other <- training(splits)
hotel_test <- testing(splits)
```


```{r}
hotel_other |>    
  count(children) |>    
  mutate(prop = n/sum(n)) 
```


```{r}
hotel_test |>    
  count(children) |>    
  mutate(prop = n/sum(n))
```



```{r}
set.seed(234)  
val_set <-
  validation_split(data = hotel_other,
                   prop = 3 / 4,
                   strata = "children") 

val_set
```


```{r}
lr_mod <-
  logistic_reg(penalty = tune(),
               mixture = 1) |>
  set_engine(engine = "glmnet") |>
  set_mode("classification")
```

```{r}
holidays <-
  c(
    "AllSouls",
    "AshWednesday",
    "ChristmasEve",
    "Easter",
    "ChristmasDay",
    "GoodFriday",
    "NewYearsDay",
    "PalmSunday"
  )

lr_recipe <-    
  recipe(children ~ ., data = hotel_other) |>    
  step_date(arrival_date) |>    
  step_holiday(arrival_date, holidays = holidays) |>    
  step_rm(arrival_date) |>    
  step_dummy(all_nominal_predictors()) |>    
  step_zv(all_predictors()) |>    
  step_normalize(all_predictors())
```

```{r}
lr_recipe |> prep() |> bake(hotel_other) |> glimpse()
```

```{r}
lr_workflow <-    
  workflow() |>    
  add_model(lr_mod) |>    
  add_recipe(lr_recipe)
```

```{r}
# automat 
lr_grid <- grid_regular(penalty(), levels = 30)  

# manualnie 
lr_grid <- tibble(penalty = 10^seq(-4, -1, length.out = 30))
```

```{r}
lr_res <-
  lr_workflow |>
  tune_grid(
    resamples = val_set,
    grid = lr_grid,
    control = control_grid(save_pred = TRUE),
    metrics = metric_set(roc_auc)
  )
```

```{r}
library(ggthemes)

lr_plot <-
  lr_res |>
  collect_metrics() |>
  ggplot(aes(penalty, mean)) +
  geom_point(size = 2) +
  geom_line(linetype = 2) +
  ylab("Pole powierzchni pod krzywa ROC") +
  scale_x_log10() +
  geom_text(aes(
    x = penalty,
    y = mean + 0.03,
    label = .config |> stringr::str_sub(20, 21)
  )) + 
  ggdark::dark_theme_dark()

lr_plot
```

```{r}
top_models <- 
  lr_res |> 
  show_best("roc_auc", n = 15) |> 
  arrange(penalty) |> 
  mutate(mean = mean |> round(x = _, digits = 3))

top_models |> gt::gt()
```

```{r}
lr_plot +
  geom_vline(
    xintercept = c(0.000853, 0.00221),
    linetype = 4,
    size = 1,
    color = "black"
  ) + 
  ggtitle("Modele o tej samej skutecznosci (roc_auc = 0.877)")
```

```{r}
lr_best <- 
  lr_res |> 
  collect_metrics() |> 
  arrange(penalty) |> 
  slice(15)

lr_best
```

```{r}
lr_auc <- 
  lr_res %>% 
  collect_predictions(parameters = lr_best) %>% 
  roc_curve(children, .pred_children) %>% 
  mutate(model = "Logistic Regression")

autoplot(lr_auc) +
  ggdark::dark_theme_dark()
```

```{r}
cores <- parallel::detectCores()
cores
```

```{r}
tidymodels_prefer()

rf_mod <-
  rand_forest(mtry = tune(),
              min_n = tune(),
              trees = 1000) |>
  set_engine(engine = "ranger",
             num.threads = cores - 1) |>
  set_mode(mode = "classification")
```

```{r}
rf_recipe <- 
  recipe(children ~ ., data = hotel_other) |> 
  step_date(arrival_date) |> 
  step_holiday(holidays = holidays) |> 
  step_rm(arrival_date)
```

```{r}
rf_workflow <- 
  workflow() |> 
  add_model(rf_mod) |> 
  add_recipe(rf_recipe)
```

```{r}
rf_mod
extract_parameter_set_dials(rf_mod)
```

```{r}
set.seed(345)
rf_res <- 
  rf_workflow |> 
  tune_grid(resamples = val_set, 
            grid = 25, 
            control = control_grid(save_pred = T),
            metrics = metric_set(roc_auc))
```

```{r}
rf_res |> show_best(n = 5)
```

```{r}
autoplot(rf_res) + 
  geom_line() + 
  geom_point(size = 2) + 
  ggdark:::dark_theme_dark()
```

```{r}
rf_best <- 
  rf_res |> select_best()
rf_best
```

```{r}
rf_auc <-
  rf_res |>
  collect_predictions(parameters = rf_best) |>
  roc_curve(children, .pred_children) |>
  mutate(model = "Random Forest")

rf_auc |> 
  autoplot() + 
  ggdark::dark_theme_dark()
```

```{r}
bind_rows(lr_auc,rf_auc) |> 
  ggplot(aes(x = 1 - specificity, y = sensitivity, col = model)) +
  geom_path(lwd = 1.5) +
  geom_abline(lty = 3) + 
  coord_equal() +
  scale_color_manual(values = c("black", "white")) +
  ggdark::dark_theme_dark()
```

```{r}
rf_best
```

```{r}
last_rf_mod <- 
  rand_forest(mtry = 8, min_n = 12, trees = 1000) |> 
  set_engine("ranger", num.threads = cores-2, importance = "impurity") |> 
  set_mode("classification")

last_rf_work <- 
  rf_workflow |> 
  update_model(last_rf_mod)

set.seed(345)
last_rf_fit <- 
  last_rf_work |> 
  last_fit(split = splits)

last_rf_fit
```

```{r}
last_rf_fit |> 
  collect_metrics()
```

```{r}
last_rf_fit |> 
  extract_fit_parsnip() |> 
  vip(num_features = 20) +
  scale_x_discrete(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0)) +
  geom_boxplot(color = "black", fill = "grey85") +
  ggdark::dark_theme_dark()
```

```{r}
last_rf_fit |> 
  collect_predictions() |> 
  roc_curve(children, .pred_children) |> 
  autoplot() +
  ggdark::dark_theme_dark()
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```







